#define _POSIX_C_SOURCE 199309L

#define RLITE_CRLF "\r\n"
#define RLITE_STR_OK "OK"
#define RLITE_STR_ERR "ERR"
#define RLITE_PONG "PONG"
#define RLITE_QUEUED "QUEUED"
#define RLITE_WRONGTYPEERR "WRONGTYPE Operation against a key holding the wrong kind of value"
#define RLITE_WRONGNUMBEROFARGUMENTS "wrong number of arguments for %s"
#define RLITE_NOKEYERR "No such key"
#define RLITE_SYNTAXERR "syntax error"
#define RLITE_SAMEOBJECTERR "source and destination objects are the same"
#define RLITE_OUTOFRANGEERR "index out of range"
#define RLITE_INVALIDMINMAXERR "min or max not valid string range item"
#define RLITE_NOSCRIPTERR "NOSCRIPT No matching script. Please use EVAL."
